export const defaultPinnedLeagues = {
  1: [
    "xjLzNo5G",
    "hYZkYQNG",
    "6PcHXsLl",
    "YTpcH4Cr",
    "x0z4oZsj",
    "A1MYWy8T",
    "ABkrguJ9",
    "x0KXIZfD",
    "fLWNsJXD",
    "8OzStwmK",
    "bcZ6ZZ9O",
    "ET7JxfI5",
    "xYqrfcAn",
    "zeSHfCx3",
    "6XkGb7p3",
    "lduLcRa9",
  ],
  2: [
    "U7C2r3rq",
    "8tWCzTJs",
    "CYj4wKu1",
    "6PaBnO2C",
    "rBG6sNck",
    "SY07m4m6",
    "zsqMQcAD",
    "jJM4VFno",
  ],
  3: [
    "2XYJ4fPF",
    "YyH9IuM5",
    "OOWWVjPH",
    "MLg7PbrE",
    "MwkSGEK6",
    "ngGo6uaf",
    "WAXLTRa4",
    "EmxmQVhl",
    "6T1YigHL",
    "Y1Aloi0c",
  ],
  4: [
    "QV1C1dg0",
    "ns05EXMO",
    "4du9pbJ1",
    "4tTPmEJT",
    "xWjXJCmG",
    "Acfuyhm3",
    "l87tyFTP",
    "KSyPnilO",
  ],
};
